name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Shellcheck
        run: shellcheck -x --severity=warning woche.sh functions.sh variables.sh tests.sh

      - name: Starting tests
        run: |
              echo Starting tests
              bash tests.sh
